# Data Preprocessing & Feature Engineering

In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler , MinMaxScaler

#Data Exploration & Pre-Processing

In [46]:
# define columns from dataframe
columns = ["age","workclass","fnlwgt","education","education_num","marital_status","occupation","relationship","race","sex","capital_gain","capital_loss","hours_per_week","native_country","income"]

In [47]:
df = pd.read_csv("/content/adult_with_headers (1).csv")
print("basic summary statistics")
display(df.describe())
print("\n  Data Tyes",df.dtypes)

basic summary statistics

                age        fnlwgt  ...  capital_loss  hours_per_week
count  32561.000000  3.256100e+04  ...  32561.000000    32561.000000
mean      38.581647  1.897784e+05  ...     87.303830       40.437456
std       13.640433  1.055500e+05  ...    402.960219       12.347429
min       17.000000  1.228500e+04  ...      0.000000        1.000000
25%       28.000000  1.178270e+05  ...      0.000000       40.000000
50%       37.000000  1.783560e+05  ...      0.000000       40.000000
75%       48.000000  2.370510e+05  ...      0.000000       45.000000
max       90.000000  1.484705e+06  ...   4356.000000       99.000000

[8 rows x 6 columns]

  Data Tyes age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [48]:
# Handling the missing values
df.replace("?",np.nan,inplace=True)

In [49]:
print("\n Misiing values before imputation",df.isnull().sum())

 Misiing values before imputation age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [50]:
"""no need to impute values as their are no null values in any column"""

'no need to impute values as their are no null values in any column'

In [51]:
# Separating columns into numerical(num) & categorical(cat)
num_cols = df.select_dtypes(include = ["int64","float64"]).columns
cat_cols = df.select_dtypes(include = ["object"]).columns

In [52]:
num_cols

Index(['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss',
       'hours_per_week'],
      dtype='object')

In [53]:
cat_cols

Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income'],
      dtype='object')

In [54]:
# scaling numerical features
df_standard_scaled = df.copy()
df_minmax_scaled = df.copy()

std_scaler = StandardScaler()
df_standard_scaled[num_cols] = std_scaler.fit_transform(df[num_cols])

mm_scaler = MinMaxScaler()
df_minmax_scaled[num_cols] = mm_scaler.fit_transform(df[num_cols])
print("\n scaling completed")

 scaling completed

# Encoding Techniques

In [55]:
#determining the category counts to decide encoding strategy
print("\n--- Unique Category Counts ---")
# Re-evaluate cat_cols after one-hot encoding in previous steps
cat_cols = df.select_dtypes(include = ["object"]).columns

for col in cat_cols:
    print(f"{col}: {df[col].nunique ()}categories")

--- Unique Category Counts ---
workclass: 9categories
education: 16categories
marital_status: 7categories
occupation: 15categories
relationship: 6categories
race: 5categories
sex: 2categories
native_country: 42categories
income: 2categories

In [56]:
# apply one-hot encoding(< 5 categories)
less_than_5_cats = [col for col in cat_cols if df[col].nunique() <= 5]
df = pd.get_dummies(df,columns=less_than_5_cats, drop_first = True)

In [57]:
#apply label encoding(>=5 categories)
# Re-evaluate cat_cols after one-hot encoding
cat_cols = df.select_dtypes(include = ["object"]).columns
more_than_5_cats = [col for col in cat_cols if df[col].nunique() >= 5]
le= LabelEncoder()
for col in more_than_5_cats:
    df[col] = le.fit_transform(df[col])
print("\n--- Encoding Complete. New Shape:---",df.shape)

--- Encoding Complete. New Shape:--- (32561, 18)

# Feature Engineering

In [58]:
# New Feature 1 : Net capital
df['net_capital'] = df['capital_gain'] - df['capital_loss']

In [60]:
df['net_capital'].head()

0    2174
1       0
2       0
3       0
4       0
Name: net_capital, dtype: int64

In [61]:
#New Feature 2: is US native
temp_df = pd.read_csv("/content/adult_with_headers (1).csv")
df["is_US_native"] = temp_df["native_country"].apply(lambda x: 1 if x == "United-States" else 0)

In [67]:
print("\n Final Features",df.columns.tolist())

 Final Features ['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'race_ Asian-Pac-Islander', 'race_ Black', 'race_ Other', 'race_ White', 'sex_ Male', 'income_ >50K', 'net_capital', 'is_US_native']